// solid-frontend/src/routes/transactions.tsx
import { For, createMemo } from 'solid-js'
import { createFileRoute } from '@tanstack/solid-router'
import { transactions, expenseList, formatMoney } from '../lib/store'

export const Route = createFileRoute('/transactions')({ component: Transactions })

function getModeBalance(mode: string) {
  let bal = 0
  for (const t of transactions) {
    if (t.payment_mode === mode) {
      if (t.type === 'Sale' || t.type === 'Income' || t.type === 'Capital') bal += t.amount
      else if (t.type === 'Purchase' || t.type === 'Expense' || t.type === 'Asset') bal -= t.amount
    }
  }
  for (const e of expenseList) {
    if (e.paid_by === mode) bal -= e.amount
  }
  return bal
}

function Transactions() {
  const cashBalance = createMemo(() => getModeBalance('Cash'))
  const bankBalance = createMemo(() => getModeBalance('Bank'))

  return (
    <div class="space-y-6">
      <div class="flex items-stretch mt-4 gap-4">
        <div class="w-1/2">
          <div class="bg-[#0dcaf0] text-white border-0 shadow-sm rounded-xl h-full">
            <div class="p-4">
              <p class="uppercase font-bold mb-1 tracking-wider text-[0.85em]">
                Cash Balance
              </p>
              <h3 class="mb-0 font-bold text-2xl">₹{formatMoney(cashBalance())}</h3>
            </div>
          </div>
        </div>
        <div class="w-1/2">
          <div class="bg-[#0d6efd] text-white border-0 shadow-sm rounded-xl h-full">
            <div class="p-4">
              <p class="uppercase font-bold mb-1 tracking-wider text-[0.85em]">
                Bank Balance
              </p>
              <h3 class="mb-0 font-bold text-2xl">₹{formatMoney(bankBalance())}</h3>
            </div>
          </div>
        </div>
      </div>

      <div class="border-0 shadow-sm rounded-lg overflow-hidden">
        <div class="bg-white pt-4 pb-3 px-4">
          <h5 class="mb-0 font-bold text-gray-600">Transaction History</h5>
        </div>
        <div class="overflow-x-auto">
          <table class="w-full text-sm">
            <thead class="bg-gray-100 text-gray-600 uppercase text-xs">
              <tr>
                <th class="py-3 pl-4 text-left">#</th>
                <th class="py-3 text-left">Date</th>
                <th class="py-3 text-left">Particulars</th>
                <th class="py-3 text-left">Type</th>
                <th class="py-3 text-left">Payment Mode</th>
                <th class="py-3 pr-4 text-right">Amount (₹)</th>
              </tr>
            </thead>
            <tbody>
              <For each={transactions.slice().reverse()}>
                {(t, i) => {
                  const modeColor =
                    t.payment_mode === 'Cash' || t.payment_mode === 'Bank'
                      ? 'text-green-600'
                      : 'text-yellow-600'
                  return (
                    <tr class="border-b border-gray-200 hover:bg-gray-50 cursor-pointer">
                      <td class="py-3 pl-4">{transactions.length - i()}</td>
                      <td class="py-3">{t.date}</td>
                      <td class="py-3">{t.particulars}</td>
                      <td class="py-3">
                        <span class="inline-block px-2 py-0.5 rounded text-xs font-bold text-white bg-gray-500">
                          {t.type}
                        </span>
                      </td>
                      <td class="py-3">
                        <span class={`inline-block px-2 py-0.5 rounded text-xs font-bold bg-gray-100 ${modeColor}`}>
                          {t.payment_mode}
                        </span>
                      </td>
                      <td class="py-3 pr-4 text-right font-bold">
                        ₹{formatMoney(t.amount)}
                      </td>
                    </tr>
                  )
                }}
              </For>
              <For each={transactions.length === 0 ? [true] : []}>
                {() => (
                  <tr>
                    <td colspan="6" class="text-center text-gray-500 py-8">
                      No transactions yet.
                    </td>
                  </tr>
                )}
              </For>
            </tbody>
          </table>
        </div>
      </div>
    </div>
  )
}

// frontend/pages/transactions.vue
<script setup lang="ts">
definePageMeta({ title: 'Transactions' })

const transactions = ref<any[]>([])
const loading = ref(false)
const cashBalance = ref(0)
const bankBalance = ref(0)

onMounted(loadAll)

async function loadAll() {
  loading.value = true
  try {
    const txns = await api().getTransactionHistory()
    transactions.value = Array.isArray(txns) ? txns : []

    const [cash, bank] = await Promise.all([
      api().getAccountBalance('Cash').catch(() => ({ balance: '0' })),
      api().getAccountBalance('Bank').catch(() => ({ balance: '0' })),
    ])
    cashBalance.value = Number(cash.balance)
    bankBalance.value = Number(bank.balance)
  } finally { loading.value = false }
}

const currency = (v: string | number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(Number(v))

function txnType(row: any) {
  const amt = Number(row.amount || row.debit || row.credit || 0)
  if (row.type) return row.type
  if ((row.debit || 0) > 0) return 'Debit'
  if ((row.credit || 0) > 0) return 'Credit'
  return amt >= 0 ? 'Credit' : 'Debit'
}

function txnAmount(row: any) {
  return Math.abs(Number(row.amount || row.debit || row.credit || 0))
}

function paymentMode(row: any) {
  return row.payment_mode || row.mode || row.paid_by || '-'
}
</script>

<template>
  <div>
    <div class="flex justify-between items-center mb-4">
      <h1 class="text-2xl font-bold">Transactions</h1>
    </div>
    <div class="grid grid-cols-1 md:grid-cols-2 gap-4 mb-4">
      <div class="rounded-xl p-5 bg-cyan-600 text-white shadow-sm">
        <h6 class="text-xs uppercase tracking-wider opacity-80 mb-2">CASH BALANCE</h6>
        <h2 class="text-2xl font-bold">{{ currency(cashBalance) }}</h2>
      </div>
      <div class="rounded-xl p-5 bg-blue-600 text-white shadow-sm">
        <h6 class="text-xs uppercase tracking-wider opacity-80 mb-2">BANK BALANCE</h6>
        <h2 class="text-2xl font-bold">{{ currency(bankBalance) }}</h2>
      </div>
    </div>
    <div class="bg-white shadow-sm rounded-lg border border-gray-200 overflow-hidden">
      <div v-if="loading" class="text-center py-4 text-gray-500">Loading...</div>
      <div v-else-if="!transactions.length" class="text-center py-4 text-gray-500">No transactions found.</div>
      <div v-else class="overflow-x-auto">
        <table class="w-full">
          <thead class="bg-gray-50">
            <tr>
              <th class="text-left px-4 py-3 font-semibold text-xs uppercase tracking-wider">#</th>
              <th class="text-left px-4 py-3 font-semibold text-xs uppercase tracking-wider">Date</th>
              <th class="text-left px-4 py-3 font-semibold text-xs uppercase tracking-wider">Particulars</th>
              <th class="text-left px-4 py-3 font-semibold text-xs uppercase tracking-wider">Type</th>
              <th class="text-left px-4 py-3 font-semibold text-xs uppercase tracking-wider">Payment Mode</th>
              <th class="text-left px-4 py-3 font-semibold text-xs uppercase tracking-wider">Amount</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-200">
            <tr v-for="(t, i) in transactions" :key="t.transaction_id || t.id || i" class="hover:bg-gray-50">
              <td class="px-4 py-3">{{ i + 1 }}</td>
              <td class="px-4 py-3">{{ t.date?.slice(0, 10) }}</td>
              <td class="px-4 py-3">{{ t.particulars || t.description || t.notes || '-' }}</td>
              <td class="px-4 py-3">
                <UBadge :color="txnType(t) === 'Debit' ? 'error' : 'success'">
                  {{ txnType(t) }}
                </UBadge>
              </td>
              <td class="px-4 py-3">{{ paymentMode(t) }}</td>
              <td :class="txnType(t) === 'Debit' ? 'px-4 py-3 text-red-600 font-medium' : 'px-4 py-3 text-emerald-600 font-medium'">
                {{ txnType(t) === 'Debit' ? '-' : '+' }}{{ currency(txnAmount(t)) }}
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>
  </div>
</template>

<style scoped>
</style>
