// frontend/pages/stock.vue
<script setup lang="ts">
import { useInventoryStore } from '~/stores/inventory'
import type { ProductResponse, ProductCreate, ProductUpdate } from '~/lib/api/client'

definePageMeta({ title: 'Stock' })

const store = useInventoryStore()
const showModal = ref(false)
const editing = ref<string | null>(null)
const form = ref<ProductCreate>({ name: '', selling_price: 0, quantity: 0, gst_rate: 0, hsn_code: '' })

function totalValue(p: ProductResponse) { return Number(p.selling_price) * p.quantity }

onMounted(() => store.fetchAll())

function openAdd() {
  editing.value = null
  form.value = { name: '', selling_price: 0, quantity: 0, gst_rate: 0, hsn_code: '' }
  showModal.value = true
}

function openEdit(p: ProductResponse) {
  editing.value = p.product_id
  form.value = {
    name: p.name,
    selling_price: Number(p.selling_price),
    quantity: p.quantity,
    gst_rate: Number(p.gst_rate),
    hsn_code: p.hsn_code,
  }
  showModal.value = true
}

async function save() {
  if (editing.value) {
    await store.update(editing.value, form.value as ProductUpdate)
  } else {
    await store.create(form.value)
  }
  showModal.value = false
}

async function confirmDelete(id: string) {
  if (confirm('Delete this product?')) await store.remove(id)
}

const currency = (v: string | number) => new Intl.NumberFormat('en-IN', { style: 'currency', currency: 'INR' }).format(Number(v))
</script>

<template>
  <div>
    <div class="flex justify-between items-center mb-4">
      <h1 class="text-2xl font-bold">Stock</h1>
      <UButton color="primary" @click="openAdd">+ Add Stock</UButton>
    </div>
    <div class="bg-white shadow-sm rounded-lg border border-gray-200 overflow-hidden">
      <div v-if="store.loading" class="text-center py-4 text-gray-500">Loading...</div>
      <div v-else-if="!store.items.length" class="text-center py-4 text-gray-500">No products found.</div>
      <div v-else class="overflow-x-auto">
        <table class="w-full">
          <thead class="bg-gray-50">
            <tr>
              <th class="text-left px-4 py-3 font-semibold text-xs uppercase tracking-wider">#</th>
              <th class="text-left px-4 py-3 font-semibold text-xs uppercase tracking-wider">Code</th>
              <th class="text-left px-4 py-3 font-semibold text-xs uppercase tracking-wider">Name</th>
              <th class="text-left px-4 py-3 font-semibold text-xs uppercase tracking-wider">Qty</th>
              <th class="text-left px-4 py-3 font-semibold text-xs uppercase tracking-wider">Price</th>
              <th class="text-left px-4 py-3 font-semibold text-xs uppercase tracking-wider">Total Value</th>
              <th class="text-left px-4 py-3 font-semibold text-xs uppercase tracking-wider">GST%</th>
              <th class="text-left px-4 py-3 font-semibold text-xs uppercase tracking-wider">HSN</th>
              <th class="text-left px-4 py-3 font-semibold text-xs uppercase tracking-wider">Actions</th>
            </tr>
          </thead>
          <tbody class="divide-y divide-gray-200">
            <tr v-for="(p, i) in store.items" :key="p.product_id" class="hover:bg-gray-50">
              <td class="px-4 py-3">{{ i + 1 }}</td>
              <td class="px-4 py-3"><code class="text-sm bg-gray-100 px-1 rounded">{{ p.item_code || '-' }}</code></td>
              <td class="px-4 py-3">{{ p.name }}</td>
              <td class="px-4 py-3">{{ p.quantity }}</td>
              <td class="px-4 py-3">{{ currency(p.selling_price) }}</td>
              <td class="px-4 py-3">{{ currency(totalValue(p)) }}</td>
              <td class="px-4 py-3">{{ p.gst_rate }}%</td>
              <td class="px-4 py-3"><code class="text-sm bg-gray-100 px-1 rounded">{{ p.hsn_code }}</code></td>
              <td class="px-4 py-3">
                <div class="flex gap-2">
                  <UButton color="primary" variant="outline" size="sm" @click="openEdit(p)">Edit</UButton>
                  <UButton color="error" variant="outline" size="sm" @click="confirmDelete(p.product_id)">Delete</UButton>
                </div>
              </td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <UModal v-model:open="showModal">
      <template #header>
        <h3 class="text-lg font-semibold">{{ editing ? 'Edit' : 'Add' }} Product</h3>
      </template>
      <div class="space-y-4">
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Name</label>
          <UInput v-model="form.name" placeholder="Product name" />
        </div>
        <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Selling Price</label>
            <UInput v-model.number="form.selling_price" type="number" step="0.01" />
          </div>
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Quantity</label>
            <UInput v-model.number="form.quantity" type="number" />
          </div>
        </div>
        <div class="grid grid-cols-1 sm:grid-cols-2 gap-4">
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">GST Rate (%)</label>
            <UInput v-model.number="form.gst_rate" type="number" step="0.1" />
          </div>
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">HSN Code</label>
            <UInput v-model="form.hsn_code" placeholder="e.g. 8471" />
          </div>
        </div>
      </div>
      <template #footer>
        <div class="flex justify-end gap-3">
          <UButton color="neutral" variant="outline" @click="showModal = false">Cancel</UButton>
          <UButton color="primary" @click="save">Save</UButton>
        </div>
      </template>
    </UModal>
  </div>
</template>

<style scoped>
</style>

// solid-frontend/src/routes/stock.tsx
import { createSignal, For, Show } from 'solid-js'
import { createFileRoute } from '@tanstack/solid-router'
import { createForm } from '@tanstack/solid-form'
import { stockList, setStockList, formatMoney } from '../lib/store'
import type { components } from '../lib/api/schema'

type ProductResponse = components['schemas']['ProductResponse']
type ProductCreate = components['schemas']['ProductCreate']

export const Route = createFileRoute('/stock')({ component: Stock })

function Stock() {
  const [showModal, setShowModal] = createSignal(false)
  const [editingId, setEditingId] = createSignal<string | null>(null)

  const form = createForm(() => ({
    defaultValues: {
      name: '',
      selling_price: 0,
      quantity: 0,
      gst_rate: 0,
      hsn_code: '',
    } as ProductCreate,
  }))

  function openNew() {
    setEditingId(null)
    form.reset()
    setShowModal(true)
  }

  function openEdit(id: string) {
    const s = stockList.find((x) => x.product_id === id)
    if (!s) return
    setEditingId(id)
    form.setFieldValue('name', s.name)
    form.setFieldValue('selling_price', Number(s.selling_price))
    form.setFieldValue('quantity', s.quantity)
    form.setFieldValue('gst_rate', Number(s.gst_rate))
    form.setFieldValue('hsn_code', s.hsn_code)
    setShowModal(true)
  }

  function handleSave() {
    const vals = form.state.values
    if (!vals.name.trim()) return
    if (editingId()) {
      setStockList(
        (s) => s.product_id === editingId(),
        'name', vals.name.trim(),
        'selling_price', String(vals.selling_price),
        'quantity', vals.quantity,
        'gst_rate', String(vals.gst_rate),
        'hsn_code', vals.hsn_code,
      )
    } else {
      setStockList(stockList.length, {
        product_id: crypto.randomUUID(),
        name: vals.name.trim(),
        selling_price: String(vals.selling_price),
        quantity: vals.quantity,
        gst_rate: String(vals.gst_rate),
        hsn_code: vals.hsn_code,
        archived: false,
      })
    }
    setShowModal(false)
  }

  function handleDelete(id: string) {
    if (!confirm('Delete this item?')) return
    setStockList(stockList.filter((s) => s.product_id !== id))
  }

  const totalValue = (s: ProductResponse) => s.quantity * Number(s.selling_price)

  return (
    <div class="space-y-6">
      <div class="border-0 shadow-sm rounded-lg overflow-hidden">
        <div class="bg-white px-4 py-3 flex items-center justify-between">
          <h5 class="mb-0 font-bold text-gray-700">Stock Inventory</h5>
          <button
            onClick={openNew}
            class="bg-blue-600 hover:bg-blue-700 text-white text-sm font-medium px-3 py-1.5 rounded transition-colors"
          >
            + Add Stock
          </button>
        </div>
        <div class="px-4 py-2 text-sm text-blue-700 bg-blue-50 border border-blue-200 rounded mx-3 mb-2">
          <strong>Tip:</strong> Click Edit to modify a stock item.
        </div>
        <div class="overflow-x-auto">
          <table class="w-full text-sm">
            <thead class="bg-gray-100 text-gray-600 uppercase text-xs">
              <tr>
                <th class="py-3 pl-4 text-left" style="width:50px">#</th>
                <th class="py-3 text-left">Name</th>
                <th class="py-3 text-right">Quantity</th>
                <th class="py-3 text-right">Selling Price (₹)</th>
                <th class="py-3 text-right">GST Rate (%)</th>
                <th class="py-3 text-left">HSN Code</th>
                <th class="py-3 text-right">Total Value (₹)</th>
                <th class="py-3 pr-4 text-center" style="width:120px">Actions</th>
              </tr>
            </thead>
            <tbody>
              <For each={stockList}>
                {(s, i) => (
                  <tr class="border-b border-gray-200 hover:bg-gray-50">
                    <td class="py-3 pl-4">{i() + 1}</td>
                    <td class="py-3 font-medium">{s.name}</td>
                    <td class="py-3 text-right">{s.quantity}</td>
                    <td class="py-3 text-right">₹{formatMoney(Number(s.selling_price))}</td>
                    <td class="py-3 text-right">{s.gst_rate}%</td>
                    <td class="py-3">{s.hsn_code || '-'}</td>
                    <td class="py-3 text-right font-bold">₹{formatMoney(totalValue(s))}</td>
                    <td class="py-3 pr-4 text-center">
                      <button
                        onClick={() => openEdit(s.product_id)}
                        class="text-blue-600 hover:text-blue-800 underline text-xs mr-2"
                      >
                        Edit
                      </button>
                      <button
                        onClick={() => handleDelete(s.product_id)}
                        class="text-red-600 hover:text-red-800 underline text-xs"
                      >
                        Delete
                      </button>
                    </td>
                  </tr>
                )}
              </For>
              <For each={stockList.length === 0 ? [true] : []}>
                {() => (
                  <tr>
                    <td colspan="8" class="text-center text-gray-500 py-8">
                      No stock items added yet.
                    </td>
                  </tr>
                )}
              </For>
            </tbody>
          </table>
        </div>
      </div>

      <Show when={showModal()}>
        <div class="fixed inset-0 z-50 flex items-center justify-center bg-black bg-opacity-40" onClick={() => setShowModal(false)}>
          <div class="bg-white rounded-lg shadow-xl w-full max-w-md mx-4" onClick={(e) => e.stopPropagation()}>
            <div class="px-4 py-3 border-b border-gray-200">
              <h5 class="mb-0 font-bold text-gray-700">{editingId() !== null ? 'Edit Stock' : 'Stock Details'}</h5>
            </div>
            <div class="p-4">
              <form.Field name="name">
                {(field) => (
                  <div class="mb-3">
                    <label class="block text-sm font-medium text-gray-700 mb-1">Name</label>
                    <input
                      type="text"
                      value={field.state.value}
                      onInput={(e) => field.handleChange(e.currentTarget.value)}
                      class="w-full border border-gray-300 rounded px-3 py-2 text-sm focus:outline-none focus:border-blue-500"
                      required
                    />
                  </div>
                )}
              </form.Field>
              <div class="flex gap-3">
                <form.Field name="selling_price">
                  {(field) => (
                    <div class="w-1/3 mb-3">
                      <label class="block text-sm font-medium text-gray-700 mb-1">Selling Price</label>
                      <input
                        type="number"
                        step="0.01"
                        min="0"
                        value={field.state.value}
                        onInput={(e) => field.handleChange(parseFloat(e.currentTarget.value) || 0)}
                        class="w-full border border-gray-300 rounded px-3 py-2 text-sm focus:outline-none focus:border-blue-500"
                        required
                      />
                    </div>
                  )}
                </form.Field>
                <form.Field name="quantity">
                  {(field) => (
                    <div class="w-1/3 mb-3">
                      <label class="block text-sm font-medium text-gray-700 mb-1">Quantity</label>
                      <input
                        type="number"
                        min="0"
                        value={field.state.value}
                        onInput={(e) => field.handleChange(parseInt(e.currentTarget.value) || 0)}
                        class="w-full border border-gray-300 rounded px-3 py-2 text-sm focus:outline-none focus:border-blue-500"
                        required
                      />
                    </div>
                  )}
                </form.Field>
                <form.Field name="gst_rate">
                  {(field) => (
                    <div class="w-1/3 mb-3">
                      <label class="block text-sm font-medium text-gray-700 mb-1">GST Rate (%)</label>
                      <input
                        type="number"
                        step="0.01"
                        min="0"
                        value={field.state.value}
                        onInput={(e) => field.handleChange(parseFloat(e.currentTarget.value) || 0)}
                        class="w-full border border-gray-300 rounded px-3 py-2 text-sm focus:outline-none focus:border-blue-500"
                      />
                    </div>
                  )}
                </form.Field>
              </div>
              <form.Field name="hsn_code">
                {(field) => (
                  <div class="mb-3">
                    <label class="block text-sm font-medium text-gray-700 mb-1">HSN Code</label>
                    <input
                      type="text"
                      value={field.state.value}
                      onInput={(e) => field.handleChange(e.currentTarget.value)}
                      class="w-full border border-gray-300 rounded px-3 py-2 text-sm focus:outline-none focus:border-blue-500"
                      placeholder="Optional"
                    />
                  </div>
                )}
              </form.Field>
              <div class="text-right mt-3 flex gap-2 justify-end">
                <button
                  onClick={() => setShowModal(false)}
                  class="px-4 py-2 text-sm border border-gray-300 rounded hover:bg-gray-50 transition-colors"
                >
                  Cancel
                </button>
                <button
                  onClick={handleSave}
                  class="px-4 py-2 text-sm bg-blue-600 text-white rounded hover:bg-blue-700 transition-colors"
                >
                  {editingId() !== null ? 'Update Item' : 'Save Item'}
                </button>
              </div>
            </div>
          </div>
        </div>
      </Show>
    </div>
  )
}
